services:
  - type: web
    name: inventario-sofka
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app  # Modificar esta línea
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production  
